Credits: Präsentiert von Team 1 - Fabian, Christian, Meike
GameName: TicTacToe
GameDescription: Ein seltsames Spiel. Der einzig gewinnbringende Zug ist, nicht zu spielen.

StartGameHuman: Spiel starten, der Mensch beginnt.
StartGameComputer: Spiel starten, die KI beginnt.

Surrender: Aufgeben.

HumanWon: Das unmögliche ist passiert. Du hast gegen den Computer gewonnen.
HumanLost: Du hast gegen den Computer verloren. Du bist schlecht und solltest dich schlecht fühlen.
Draw: Niemand hat gewonnen.