Credits: Brought to you by Team 1 - Fabian, Christian, Meike
GameName: TicTacToe
GameDescription: A strange game. The only winning move is not to play.

StartGameHuman: Start playing, human begins.
StartGameComputer: Start playing, computer begins.

Surrender: Surrender

HumanWon: The impossible happened. You won against the computer.
HumanLost: You lost against the computer. You are bad and you should feel bad.
Draw: Nobody won.