Credits: Präsentiert von Team 1 - Fabian, Christian, Meike
GameName: Zahlenraten
GameDescription: Wer suchet, der findet.

LinkHome: Zurück zur Startseite

HelpText: Ich werde mir eine Zahl zwischen 1 and 100 ausdenken und du musst sie mit möglichst wenig Versuchen erraten.
StartGuessing: Spiel direkt starten
TweakSettings: Ich möchte die Regeln anpassen

PleaseGuess: Bitte rate eine Zahl:
SubmitGuess: Vermutung senden!