Credits: Präsentiert von Team 1 - Fabian, Christian, Meike
GameName: Zahlenraten
GameDescription: Wer suchet, der findet.

LinkHome: Zurück zur Startseite

HelpText: Ich werde mir eine Zahl zwischen 1 and 100 ausdenken und du musst sie mit möglichst wenig Versuchen erraten.
StartGuessing: Spiel direkt starten
TweakSettings: Ich möchte die Regeln anpassen

RandomRange: Wertebereich:
LowerBound: Untergrenze:
UpperBound: Obergrenze:
SetRules: Regeln festlegen und starten!
InvalidRange: Der angegebene Bereich ist ungültig.
NoInput: Bitte gib den Bereich der Zufallszahl an, die ich mir ausdenken soll.

PleaseGuess: Bitte rate eine Zahl:
SubmitGuess: Vermutung senden!
Guess: Meine Vermutung: 
WrongGuess g: Du hast die Zahl #{show g} geraten.
CorrectGuess g: Du hast die Zahl #{show g} geraten - das ist richtig!
NumIsGreater: Meine Zahl ist größer.
NumIsLess: Meine Zahl ist kleiner.
TotalGuesses i: Anzahl Versuche: #{show i}

GuessHistory: Du hast die folgenden Zahlen geraten:
GuessHistoryItem i@Int: #{show i}