Credits: Brought to you by Team 1 - Fabian, Christian, Meike
GameName: Guess The Number
GameDescription: Seek and thou shalt find.

LinkHome: Take me to the home page.

HelpText: I will think of a number between 1 and 100 and your goal is to guess it with as few tries as possible.
StartGuessing: Just start the game
TweakSettings: I'd like to adjust the rules

PleaseGuess: Please guess a number:
SubmitGuess: Submit guess!
Guess: My guess: 
LastGuess g@Int: You guessed number #{show g}
