Credits: Prezentita de teamo 1 - Fabian, Christian, Meike
GameName: Divenu la nombro
GameDescription: Kiu serĉas, trovas.

LinkHome: Reen al la komenco

HelpText: Mi koncipos unu nombro inter 1 kaj 100 kiu vi devos diveni kun malmultajn klopodojn.
StartGuessing: Komencu ludon rekte
TweakSettings: Ŝanĝi la regulojn

RandomRange: Rango de valoroj:
LowerBound: Suba limo:
UpperBound: Supra limo:
SetRules: Difinu regulojn kaj komencu!
InvalidRange: La specifita rango estas nevalida.
NoInput: Bonvolu entajpu la rango de la hazarda numero kiu mi devos koncipi.

PleaseGuess: Bonvolu divenu unu nombro:
SubmitGuess: Submetu diveno!
Guess: Mia diveno:
WrongGuess g@Int: Vi divenis la nombro #{show g}.
NumIsGreater: Mia nombro estas pli granda ol via diveno.
NumIsLess: Mia nombro estas malpli granda ol via diveno.
TotalGuesses i@Int: Numero de divenoj: #{show i}

CorrectGuess g@Int: Vi divenis la nombro #{show g} - tio estas korekta!
GuessHistory: Vi divenis la sekvajn nombrojn: