Credits: Facta per turma I - Fabian, Christian et Meike
GameName: Suspicare Numerum
GameDescription: Qui quaerit, qui inveniat.

LinkHome: Redde ad exordium!

HelpText: Excogito numerum, maior quam unum, sed minor quam centum. Suspicare hunc numerum.
StartGuessing: Ludus Incipiat!
TweakSettings: Cupio Mutare Regulas

RandomRange: Limites Numeri
LowerBound: Limes Inferior:
UpperBound: Limes Superior:
SetRules: Ludus Incipiat!
InvalidRange: Limites Mendosi Sunt!
NoInput: Assigna Limites!

PleaseGuess: Suspicare
SubmitGuess: Mitte suspicionem!
Guess: Mea suspicio: 
WrongGuess g@Int: Suspexisti numerum falsum #{showModernRoman g}.
NumIsGreater: Meus numerus maior est.
NumIsLess: Meus numerus minor est.
TotalGuesses i@Int: Numerus attentationum: #{showModernRoman i}

CorrectGuess g@Int: Suspexisti meum numerum #{showModernRoman g}!
GuessHistory: Numeri attemptati:
GuessHistoryItem i@Int: #{showModernRoman i}