Credits: facta per turma I - Fabian, Christian et Meike
GameName: Suspicare Numerum
GameDescription: Qui quaerit, qui inveniat.

LinkHome: Redde ad exordium!

HelpText: Excogito numerum, maior quam unum, sed minor quam centum. Suspicare hic numerum.
StartGuessing: ludus incipiat
TweakSettings: cupio mutare regulas

RandomRange: limites numeri
LowerBound: limes inferior:
UpperBound: limes superior:
SetRules: ludus incipiat!
InvalidRange: limites mendosi sunt!
NoInput: assigna limites!

PleaseGuess: Suspicare
SubmitGuess: Mitte suspicionem!
Guess: Mea suspicio: 
WrongGuess g@Int: suspexisti numerum falsum #{showModernRoman g}.
NumIsGreater: Meus numerus maior est.
NumIsLess: Meus numerus minor est.
TotalGuesses i@Int: Numerus attentationum: #{showModernRoman i}

CorrectGuess g@Int: suspexisti meum numerum #{showModernRoman g}!
GuessHistory: Numeri attemptati:
GuessHistoryItem i@Int: #{showModernRoman i}